--Suppose you work for a company that sells products online. 
--Your team is responsible for analyzing sales data to identify trends and patterns, and to make recommendations for improving the company's sales performance. 
--You have been tasked with exploring the sales data using SQL.

--Creating the required Table schema
CREATE TABLE sales (
  id INT,
  sale_date DATE,
  product VARCHAR(50),
  quantity INT,
  revenue DECIMAL(10,2)
);

--Inserting Some records

INSERT INTO sales (id, sale_date, product, quantity, revenue)
VALUES
  (1, '2021-01-01', 'Product A', 10, 100.00),
  (2, '2021-01-02', 'Product B', 5, 50.00),
  (3, '2021-01-03', 'Product C', 15, 150.00),
  (4, '2021-01-04', 'Product A', 8, 80.00),
  (5, '2021-01-05', 'Product B', 12, 120.00),
  (6, '2021-01-06', 'Product C', 20, 200.00),
  (7, '2021-01-07', 'Product A', 6, 60.00),
  (8, '2021-01-08', 'Product B', 18, 180.00),
  (9, '2021-01-09', 'Product C', 10, 100.00),
  (10, '2021-01-10', 'Product A', 4, 40.00);

-- Checking the data
select * from sales;

-- Grouping the data based on Product to check Max(quantity) sold
-- and total revenue generated by the product
/*Observations
1) Product C sold maximum items
2) Product C generated max revenue
3) Product A sold least
4) Product A generated least revenue
5) Per product Price. Since C is being max and hence we can increase the price from 10 to 12.
*/
select product, sum(quantity) as total_quantity_sold, sum(revenue) as total_revenue, (sum(revenue) / sum(quantity)) as per_prod_cost from sales 
group by product 
order by product

/*
Extras:-
1) Which product was sold on jan 2nd
2) What was the total revenue for Product C?
3) Which days had revenue greater than $150?
4) Which products had a total quantity sold greater than 30?
5) What was the average revenue per sale for Product B?
6) Which products had a revenue per sale greater than $15?
*/
-- 1)
select product from sales
where sale_date = '2021-01-02'

-- 2)
select product, sum(revenue) as total_revenue_C from sales 
where product = 'Product C' 
group by product;

-- 3)
select sale_date from sales where revenue > 150;

-- 4)
select product, sum(quantity) as quantity from sales 
group by product 
having sum(quantity) > 30;

-- 5)
select product, avg(revenue) as revenue from sales 
where product = 'Product B'
group by product; 

-- 6)
SELECT product FROM sales 
GROUP BY product 
HAVING AVG(revenue) > 15;











